workflows:
  android-workflow:
    name: Build APK
    instance_type: mac_mini_m1
    scripts:
      - name: Get dependencies
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
